/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/login`; params?: Router.UnknownInputParams; } | { pathname: `/admin/blacklist`; params?: Router.UnknownInputParams; } | { pathname: `/admin/clients`; params?: Router.UnknownInputParams; } | { pathname: `/admin/livreur`; params?: Router.UnknownInputParams; } | { pathname: `/admin/orders`; params?: Router.UnknownInputParams; } | { pathname: `/admin/pricing`; params?: Router.UnknownInputParams; } | { pathname: `/admin/produits`; params?: Router.UnknownInputParams; } | { pathname: `/catalogue`; params?: Router.UnknownInputParams; } | { pathname: `/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/livreur`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/login/client`; params?: Router.UnknownInputParams; } | { pathname: `/login/livreur`; params?: Router.UnknownInputParams; } | { pathname: `/login/parent`; params?: Router.UnknownInputParams; } | { pathname: `/parametres`; params?: Router.UnknownInputParams; } | { pathname: `/parent`; params?: Router.UnknownInputParams; } | { pathname: `/verify`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/login`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/blacklist`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/clients`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/livreur`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/orders`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/pricing`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/produits`; params?: Router.UnknownOutputParams; } | { pathname: `/catalogue`; params?: Router.UnknownOutputParams; } | { pathname: `/checkout`; params?: Router.UnknownOutputParams; } | { pathname: `/livreur`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/login/client`; params?: Router.UnknownOutputParams; } | { pathname: `/login/livreur`; params?: Router.UnknownOutputParams; } | { pathname: `/login/parent`; params?: Router.UnknownOutputParams; } | { pathname: `/parametres`; params?: Router.UnknownOutputParams; } | { pathname: `/parent`; params?: Router.UnknownOutputParams; } | { pathname: `/verify`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/admin/login${`?${string}` | `#${string}` | ''}` | `/admin/blacklist${`?${string}` | `#${string}` | ''}` | `/admin/clients${`?${string}` | `#${string}` | ''}` | `/admin/livreur${`?${string}` | `#${string}` | ''}` | `/admin/orders${`?${string}` | `#${string}` | ''}` | `/admin/pricing${`?${string}` | `#${string}` | ''}` | `/admin/produits${`?${string}` | `#${string}` | ''}` | `/catalogue${`?${string}` | `#${string}` | ''}` | `/checkout${`?${string}` | `#${string}` | ''}` | `/livreur${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/login/client${`?${string}` | `#${string}` | ''}` | `/login/livreur${`?${string}` | `#${string}` | ''}` | `/login/parent${`?${string}` | `#${string}` | ''}` | `/parametres${`?${string}` | `#${string}` | ''}` | `/parent${`?${string}` | `#${string}` | ''}` | `/verify${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/login`; params?: Router.UnknownInputParams; } | { pathname: `/admin/blacklist`; params?: Router.UnknownInputParams; } | { pathname: `/admin/clients`; params?: Router.UnknownInputParams; } | { pathname: `/admin/livreur`; params?: Router.UnknownInputParams; } | { pathname: `/admin/orders`; params?: Router.UnknownInputParams; } | { pathname: `/admin/pricing`; params?: Router.UnknownInputParams; } | { pathname: `/admin/produits`; params?: Router.UnknownInputParams; } | { pathname: `/catalogue`; params?: Router.UnknownInputParams; } | { pathname: `/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/livreur`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/login/client`; params?: Router.UnknownInputParams; } | { pathname: `/login/livreur`; params?: Router.UnknownInputParams; } | { pathname: `/login/parent`; params?: Router.UnknownInputParams; } | { pathname: `/parametres`; params?: Router.UnknownInputParams; } | { pathname: `/parent`; params?: Router.UnknownInputParams; } | { pathname: `/verify`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
